global:
  scrape_interval: 1s
  scrape_timeout: 1s
scrape_configs:
  - job_name: target
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api1:8080", "api2:8080", "reservation:8080", "payment:8080", "worker:8080", "mock-pg:8080"]
